# Generated by Django 3.2.4 on 2021-06-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=230)),
                ('code', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='customer-pic')),
                ('address', models.CharField(max_length=250)),
                ('type_custumer', models.CharField(choices=[('NORMAL', 'NORMAL'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM')], default='NORMAL', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('delivered_date', models.DateTimeField()),
                ('urgent', models.BooleanField(default=False)),
                ('warehouse', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('store_code', models.CharField(blank=True, max_length=30)),
                ('partner_code', models.CharField(blank=True, max_length=30)),
                ('detail', models.CharField(blank=True, max_length=70)),
                ('quantity', models.PositiveIntegerField()),
                ('type_order', models.CharField(choices=[('DISTRIBUTION CENTER', 'DISTRIBUTION CENTER'), ('BRANCH', 'BRANCH'), ('ASSOCIATED COMPANY', 'ASSOCIATED COMPANY')], default='BRANCH', max_length=30)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
