version: '3.7'

services:
  db_postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    # depends_on: 
    #   - react
  # react:
  #   build: 
  #       context: .
  #       dockerfile: ./.docker/react/Dockerfile
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes: 
  #     - ./frontend:/frontend
  #     - '/frontend/node_modules'

  django:
    build: 
        context: .
        dockerfile: ./.docker/django/Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
        - .:/django
    depends_on:
       - db_postgres 
       
       

  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - django
    volumes: 
        - .:/nginx



volumes:
  .:
  db_data: